---
name: Docker

on:
  push:
    branches: [ 'main' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildah
        run: sudo apt-get -y install buildah
      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
      - name: Build Docker Image
        run: |
          . /etc/profile.d/nix.sh
          buildah login -u "famedly-ci" -p "${{ secrets.registry_password || secrets.GITHUB_TOKEN }}" "docker-oss.nexus.famedly.de"
          buildah pull docker-archive:$(nix-build)
          buildah tag proxy46 "docker-oss.nexus.famedly.de/proxy46"
          buildah push -f v2s2 --all "docker-oss.nexus.famedly.de/proxy46"
